site_name: Бобкин стрит
theme:
  name: terminal
  palette: pink
nav:
  - Домашняя: index.md
  - Об: about.md
markdown_extensions:
    # Python Markdown  
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: "#"
      permalink_title: Anchor link to this section for reference

  # PyMdown Extensions
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: 
        - docs